version: "3"

services:
  app:
    image: specialaro/restorix:latest # Official image in: bestporto/bestporto-pa:latest
    container_name: restorix
    restart: always
    environment:
      - SERVER_BASEURL=http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
